### ISSUE TITLE
bug: pnpm run dev not working with characterfiles

### ISSUE THREAD

**Issue by harperaa** [RubyResearch/Agent#1452]
**Describe the bug**
I would like to use dev mode, and turbo to watch for file changes, for faster development.  I have been trying to get pnpm run dev to run with a character file, to no avail.  It runs fine with default agent (no arguments), but does not appear to accept the command line arguments of --characters.

**To Reproduce**

trying pnpm run dev --character characters/eliza-code-assistant.character.json yields the following output and error.

```bash
% pnpm run dev --characters characters/eliza-code-assistant.character.json
...
...
@elizaos/plugin-solana:build: DTS Build start
@elizaos/plugin-solana:build: DTS ⚡️ Build success in 3729ms
@elizaos/plugin-solana:build: DTS dist/index.d.ts 15.88 KB

 Tasks:    45 successful, 45 total
Cached:    45 cached, 45 total
  Time:    340ms >>> FULL TURBO

(node:65388) ExperimentalWarning: CommonJS module /Users/allenharper/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /Users/allenharper/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[nodemon] 3.1.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): packages/client-direct/dist/**/*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `pnpm --filter "@elizaos/agent" start --isRoot`

> @elizaos/core@0.1.7-alpha.1 dev /Users/allenharper/Dropbox/code/eliza/packages/core
> tsup --format esm --dts --watch "--characters" "characters/eliza-code-assistant.character.json"


> @elizaos/client-direct@0.1.7-alpha.1 dev /Users/allenharper/Dropbox/code/eliza/packages/client-direct
> tsup --format esm --dts --watch "--" "--characters" "characters/eliza-code-assistant.character.json"


> eliza-client@0.1.7-alpha.1 dev /Users/allenharper/Dropbox/code/eliza/client
> vite "--" "--characters" "characters/eliza-code-assistant.character.json"


> @elizaos/plugin-code-assistant@0.1.7-alpha.1 dev /Users/allenharper/Dropbox/code/eliza/packages/plugin-code-assistant
> tsup --format esm --dts --watch "--" "--characters" "characters/eliza-code-assistant.character.json"

CACError: Unknown option `--characters`
    at Command.checkUnknownOptions (/Users/allenharper/Dropbox/code/eliza/node_modules/cac/dist/index.js:404:17)
    at CAC.runMatchedCommand (/Users/allenharper/Dropbox/code/eliza/node_modules/cac/dist/index.js:602:13)
    at main (/Users/allenharper/Dropbox/code/eliza/node_modules/tsup/dist/chunk-SNM7IVOJ.js:148:13)
    at Object.<anonymous> (/Users/allenharper/Dropbox/code/eliza/node_modules/tsup/dist/cli-default.js:12:23)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
 ELIFECYCLE  Command failed with exit code 1.

> @elizaos/agent@0.1.7-alpha.1 start /Users/allenharper/Dropbox/code/eliza/agent
> node --loader ts-node/esm src/index.ts "--isRoot"

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v8.3.5
...
```

then, it proceeds to load defaultAgent...

**Expected behavior**
I expect it to pick up the character file, launch agent, and enter turbo watch of those files... it runs correctly, if I use pnpm start --characters ...

Instead, it won't launch with character file and defaults back to defaultAgent...when in dev mode.

**Screenshots**

**Additional context**

**Comment by tcm390** [comment]
@harperaa hello I just tested with the latest `develop` branch it works, could you kindly confirm?

**Comment by jaakjuu1** [comment]
it works fine at first. But after adding a custom plugin the dev mode starts with the default Character.
